
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CategoriesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  image_url: 'image_url',
  article_count: 'article_count',
  sort_order: 'sort_order',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.HotSearchKeywordsScalarFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  hot_score: 'hot_score',
  is_active: 'is_active',
  sort_order: 'sort_order',
  created_at: 'created_at'
};

exports.Prisma.ArticlesScalarFieldEnum = {
  id: 'id',
  title: 'title',
  summary: 'summary',
  cover_url: 'cover_url',
  category_id: 'category_id',
  author_id: 'author_id',
  author_name: 'author_name',
  author_avatar: 'author_avatar',
  tags: 'tags',
  views: 'views',
  likes: 'likes',
  comments_count: 'comments_count',
  is_top: 'is_top',
  read_time: 'read_time',
  published_at: 'published_at',
  is_published: 'is_published',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.RefreshTokensScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  refresh_token: 'refresh_token',
  client_ip: 'client_ip',
  expires_at: 'expires_at',
  revoked: 'revoked',
  created_at: 'created_at'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password_hash: 'password_hash',
  password_algorithm: 'password_algorithm',
  email: 'email',
  nickname: 'nickname',
  avatar: 'avatar',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.ArticleContentBlocksScalarFieldEnum = {
  id: 'id',
  article_id: 'article_id',
  block_type: 'block_type',
  content: 'content',
  sort_order: 'sort_order',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.ArticleLikesScalarFieldEnum = {
  id: 'id',
  article_id: 'article_id',
  user_id: 'user_id',
  created_at: 'created_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.CategoriesOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  image_url: 'image_url'
};

exports.Prisma.HotSearchKeywordsOrderByRelevanceFieldEnum = {
  id: 'id',
  keyword: 'keyword'
};

exports.Prisma.ArticlesOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  summary: 'summary',
  cover_url: 'cover_url',
  category_id: 'category_id',
  author_id: 'author_id',
  author_name: 'author_name',
  author_avatar: 'author_avatar',
  tags: 'tags'
};

exports.Prisma.RefreshTokensOrderByRelevanceFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  refresh_token: 'refresh_token',
  client_ip: 'client_ip'
};

exports.Prisma.UsersOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  password_hash: 'password_hash',
  password_algorithm: 'password_algorithm',
  email: 'email',
  nickname: 'nickname',
  avatar: 'avatar'
};

exports.Prisma.ArticleContentBlocksOrderByRelevanceFieldEnum = {
  id: 'id',
  article_id: 'article_id',
  block_type: 'block_type',
  content: 'content'
};

exports.Prisma.ArticleLikesOrderByRelevanceFieldEnum = {
  id: 'id',
  article_id: 'article_id',
  user_id: 'user_id'
};


exports.Prisma.ModelName = {
  Categories: 'Categories',
  HotSearchKeywords: 'HotSearchKeywords',
  Articles: 'Articles',
  RefreshTokens: 'RefreshTokens',
  Users: 'Users',
  ArticleContentBlocks: 'ArticleContentBlocks',
  ArticleLikes: 'ArticleLikes'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
